### ISSUE TITLE
Non optimal webfont usage

### ISSUE THREAD

**Issue by santhoshtr** [meenaviyal/comicmachine#23]
``` css

@font-face {
    font-family: 'Rachana';
    src: url('https://dl.dropboxusercontent.com/u/8198933/Fonts/Rachana-Regular.woff')
}
```
- woff is old font format. Use woff2 format and fallback to woff. saves around 30% bandwidth.
- use src:local () so that localfonts are used and does not force download from server always

You can refer https://smc.org.in/fonts/css/fonts.css for some samples.
